config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  scope '/admin' do
    resources :users
  end

  resources :articles do
    resources :comments, only: %i[create destroy]  
  end
  
  resources :roles

  root to: 'articles#index'

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  has_rich_text :body

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_article

    def create
        @article.comments.create(comment_params.to_h.merge!({ user_id: current_user.id }))
        redirect_to article_path(@article), notice: 'Comment was successfully created.'
    end

    def destroy 
        comment = @article.comments.find(params[:id])
        
        comment.destroy 
        redirect_to article_path(@article), notice: 'Comment was successfully destroyed.'
    end

    private 

    def comment_params
        params.require(:comment).permit(:body)
    end

    def set_article
        @article = Article.find(params[:article_id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="card-comment">
    <div class="">
        <h4><%= month_day_comma_year(comment.created_at) %></h4>
        <p class="card-email"><%= comment.user.email %></p>
        <p class="card-text"><%= comment.body %></p>
    </div>

    <div>
        <% if can? :destroy, comment %>
            <%= link_to 'Destroy', article_comment_path(@article, comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn-default btn-sm btn-danger" %>
        <% end %>
    </div>
</div>

app/views/comments/_form.html.erb
<h3>Add a Comment: </h3>
<%= form_with model: [@article, @comment] do |form| %>
  <div class="comment-field">
    <%= form.rich_text_area :body, placeholder: "Write something..." %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: 'btn-default btn-success' %>
  </div>
<% end %>

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
    <%= render @comments %>
<% end %>